version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.local.conf
    depends_on:
      - auth-service
      - billing-service
      - payment-service
      - property-service
    networks:
      - beenaport-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - auth-db
    networks:
      - beenaport-network

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - auth-db
    networks:
      - beenaport-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/paymentdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - BILLING_SERVICE_URL=http://billing-service:8082
    depends_on:
      - payment-db
    networks:
      - beenaport-network

  property-service:
    build: ./property-service
    container_name: property-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://property-db:5432/propertydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - AUTH_SERVICE_URL=http://auth-service:8081
    depends_on:
      - property-db
    networks:
      - beenaport-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    networks:
      - beenaport-network

  property-db:
    image: postgres:15
    container_name: property-db
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    networks:
      - beenaport-network

  billing-db:
    image: postgres:15
    container_name: billing-db
    environment:
      POSTGRES_DB: billingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    networks:
      - beenaport-network

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    networks:
      - beenaport-network

networks:
  beenaport-network:
    driver: bridge