server:
  port: 8082
  servlet:
    context-path: /api/v1/billing

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/billingdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: UD/VbTB8BRa2DQfy93QXr9yAe0qZEkeeRWezRKVlf9U=
  system-token-expiry: 3600

property:
  service:
    url: ${PROPERTY_SERVICE_URL:http://localhost:8084}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springdoc: DEBUG