# events{}
#
# http {
#
#     upstream auth_service {
#         server auth-service:8080;
#     }

#     upstream property_service {
#         server property-service:8081;
#     }
#
#     upstream billing_service {
#         server billing-service:8082;
#     }
#
#     upstream payment_service {
#         server payment-service:8083;
#     }
#
#     server {
#         listen 80;
#
# #             add_header 'Access-Control-Allow-Origin' '*' always;
#
#         location /api/auth/ {
#             proxy_pass http://auth_service/;
#
#             proxy_set_header Host localhost;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         }

#         location /api/properties/ {
#             proxy_pass http://property_service/;
#         }
#
#         location /api/billing/ {
#             proxy_pass http://billing_service/;
#         }
#
#         location /api/payments/ {
#             proxy_pass http://payment_service/;
#         }
#     }
# }

server {
        listen 80;

            add_header 'Access-Control-Allow-Origin' '*' always;

        location /api/auth/ {
            proxy_pass http://auth_service/;
        }
}