server:
  port: 8084
  servlet:
    context-path: /api/v1/property

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROPERTY}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

auth:
  service:
    url: ${AUTH_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    root: WARN
    az.beenaport: INFO